my_dict = {'banana': 3, 'apple': 5, 'cherry': 2}
print("Original Dictionary:", my_dict)
print()
tuple_list = list(my_dict.items())
print("Convert to Tuples:", tuple_list)
print()
sorted_list = sorted(tuple_list, key=lambda x: x[1])
print("Sorted (by value):", sorted_list)
print()
new_dict = dict(sorted_list)
print("Convert back to Dictionary:", new_dict)
